-- DROP DATABASE bank;
use instrumentos;
CREATE TABLE `ACTIVOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(30) NOT NULL,
  `MERCADO` varchar(30) NOT NULL,
  `DESCRIPCCION` varchar(30),
  `TICKERBLOOMBERG` varchar(50) NOT NULL UNIQUE,
  `ACTIVO` Boolean NOT NULL DEFAULT 1,
  `LASTUPDATE`DATE,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PRECIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRECIO` int(30) NOT NULL,
  `ACTIVO_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ACTIVO_ID`) REFERENCES `ACTIVOS`(`ID`)
);

CREATE TABLE `USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(30) NOT NULL UNIQUE,
  `APELLIDOS` varchar(10) NOT NULL,
  `ROL` varchar(15) NOT NULL UNIQUE,
  PRIMARY KEY (`ID`)
);
