-- DROP DATABASE instrumentos;
CREATE DATABASE instrumentos;
use instrumentos;

CREATE TABLE `ACTIVOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(30) NOT NULL UNIQUE,
  `NOMBRE` varchar(30) NOT NULL,
  `MERCADO` varchar(30) NOT NULL,
  `DESCRIPCCION` varchar(30),
  `TICKERBLOOMBERG` varchar(50) NOT NULL UNIQUE,
  `ACTIVO` Boolean NOT NULL DEFAULT 1,
  `LASTUPDATE` DATE,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PRECIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRECIO` int(30) NOT NULL,
  `ACTIVO_ID` int(11) NOT NULL,
  `LASTUPDATE` DATE,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ACTIVO_ID`) REFERENCES `ACTIVOS`(`ID`)
);

CREATE TABLE `USUARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(30) NOT NULL UNIQUE,
  `NOMBRE` varchar(30) NOT NULL UNIQUE,
  `APELLIDOS` varchar(10) NOT NULL,
  `ROL` varchar(15) NOT NULL,
  `LASTUPDATE` DATE,
  PRIMARY KEY (`ID`)
);

INSERT INTO ACTIVOS (NOMBRE, CODE, MERCADO, DESCRIPCCION, TICKERBLOOMBERG, ACTIVO, LASTUPDATE) VALUES ('Apple','REF00001', 'NASDAQ', 'Empresa de tecnologia', 'AAPL US Equity', 1, now());
INSERT INTO ACTIVOS (NOMBRE, CODE, MERCADO, DESCRIPCCION, TICKERBLOOMBERG, ACTIVO, LASTUPDATE) VALUES ('Microsoft','REF00002', 'NASDAQ', 'Empresa de tecnologia', 'MSFT US Equity', 1, now());
INSERT INTO ACTIVOS (NOMBRE, CODE, MERCADO, DESCRIPCCION, TICKERBLOOMBERG, ACTIVO, LASTUPDATE) VALUES ('Amazon','REF00003', 'NASDAQ', 'Empresa de tecnologia', 'AMZN US Equity', 1, now());

INSERT INTO PRECIOS (PRECIO, ACTIVO_ID, LASTUPDATE) VALUES (100, 1, now());
INSERT INTO PRECIOS (PRECIO, ACTIVO_ID, LASTUPDATE) VALUES (200, 2, now());
INSERT INTO PRECIOS (PRECIO, ACTIVO_ID, LASTUPDATE) VALUES (300, 3, now());

INSERT INTO USUARIOS (CODE, NOMBRE, APELLIDOS, ROL, LASTUPDATE) VALUES ('000','admin', 'admin', 'admin', now());
INSERT INTO USUARIOS (CODE, NOMBRE, APELLIDOS, ROL, LASTUPDATE) VALUES ('999','user', 'user', 'user', now());
INSERT INTO USUARIOS (CODE, NOMBRE, APELLIDOS, ROL, LASTUPDATE) VALUES ('123','javi', 'hernandez', 'admin', now());



