-- DROP DATABASE bank;
use instrumentos;

INSERT INTO ACTIVOS (NOMBRE, MERCADO, DESCRIPCCION, TICKERBLOOMBERG, ACTIVO, LASTUPDATE) VALUES ('Apple', 'NASDAQ', 'Empresa de tecnologia', 'AAPL US Equity', 1, '2023-05-18');
INSERT INTO ACTIVOS (NOMBRE, MERCADO, DESCRIPCCION, TICKERBLOOMBERG, ACTIVO, LASTUPDATE) VALUES ('Microsoft', 'NASDAQ', 'Empresa de tecnologia', 'MSFT US Equity', 1, '2023-05-18');
INSERT INTO ACTIVOS (NOMBRE, MERCADO, DESCRIPCCION, TICKERBLOOMBERG, ACTIVO, LASTUPDATE) VALUES ('Amazon', 'NASDAQ', 'Empresa de tecnologia', 'AMZN US Equity', 1, '2023-05-18');

INSERT INTO PRECIOS (PRECIO, ACTIVO_ID) VALUES (100, 1);
INSERT INTO PRECIOS (PRECIO, ACTIVO_ID) VALUES (200, 2);
INSERT INTO PRECIOS (PRECIO, ACTIVO_ID) VALUES (300, 3);

INSERT INTO USUARIOS (NOMBRE, APELLIDOS, ROL) VALUES ('admin', 'admin', 'admin');
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, ROL) VALUES ('user', 'user', 'user');
